name: Theme Cards Site CD

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Generate Site
        run: |
          mkdir ./dist
          git clone https://github.com/ChrAlpha/theme-cards-docs docs
          git clone https://github.com/ChrAlpha/theme-cards-demo demo
          cd ./docs
          git clone https://github.com/ChrAlpha/hexo-theme-cards themes/cards
          npm i && npm run build
          cp -rf ./public ../dist
          cd ../demo
          npm i && npm run build
          cp -rf ./public ../dist/demo
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: theme-cards.ichr.me
          allow_empty_commit: true
          force_orphan: true
